import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1280, height: 900 } });
await p.goto("http://localhost:3000/sign-in", { waitUntil: "networkidle" });
await p.locator('button:has-text("Create account")').first().click();
await p.fill('input[type="email"]', `chat+${Date.now()}@cropconnect.test`);
await p.fill('input[type="password"]', "test123456");
await p.locator('button[type="submit"]').click();
await p.waitForURL("**/app", { timeout: 20000 });
await p.waitForTimeout(2500);
await p.locator('button[aria-label="Chat with Sage"]').click();
await p.waitForTimeout(500);
await p.locator('button:has-text("What should I source next?")').click();
await p.waitForTimeout(1200);
await p.screenshot({ path: "scripts/chat.png" });
await b.close(); console.log("shot done");
