import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1280, height: 720 } });
await p.goto("file:///Users/keshavkrishnan/Claude/CropConnect2/pitch/cropconnect-deck.html", { waitUntil: "networkidle" });
await p.waitForTimeout(900);
const s = await p.locator(".slide").all();
console.log("slides:", s.length);
await s[4].screenshot({ path: "pitch/preview-opportunity.png" });
await s[6].screenshot({ path: "pitch/preview-whynow.png" });
await p.pdf({ path: "pitch/cropconnect-deck.pdf", width: "1280px", height: "720px", printBackground: true });
await b.close(); console.log("done");
